-- City-wise stock tracking needs a real ledger — finished-goods stock in the
-- production system (production.v_fg_stock) is a single central number per
-- SKU with no location dimension, so there was nothing to base a per-city
-- breakdown on. This adds a requisition workflow instead: an admin or
-- regional sales head requests stock for their city, an admin approves it
-- (editing quantities to match actual factory availability/dispatch), and
-- approved quantities become the "stock sent to that city" side of the
-- ledger. The "stock used" side is derived from order_lines on orders that
-- have reached invoiced/delivered status (see city_stock_summary() in
-- order_engine.py) — no new table needed for that half.
create table sales.stock_requests (
  id bigint generated by default as identity primary key,
  city text not null,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  requested_by bigint not null references sales.users(id),
  approved_by bigint references sales.users(id),
  notes text,
  created_at timestamptz not null default now(),
  approved_at timestamptz
);

create table sales.stock_request_lines (
  id bigint generated by default as identity primary key,
  request_id bigint not null references sales.stock_requests(id) on delete cascade,
  sku_id bigint not null references sales.skus(id),
  requested_qty numeric not null check (requested_qty > 0),
  approved_qty numeric check (approved_qty is null or approved_qty >= 0)
);

create index stock_requests_city_status_idx on sales.stock_requests (city, status);
create index stock_request_lines_request_id_idx on sales.stock_request_lines (request_id);
create index stock_request_lines_sku_id_idx on sales.stock_request_lines (sku_id);
